### ISSUE TITLE
[BUG] MD5 algorithm used for SetEncryptionKey

### ISSUE THREAD

**Issue by harshkolhatkar** [MrWong99/gitscanner#59]
### Describe the bug
The SetEncryptionKey function calls md5 hashing algorithm. md5 is known to have issues and isn't the best of hashing algorithms. 

### Expected behavior
A known secure hashing algorithm should be used like sha256 or sha512

**Comment by harshkolhatkar** [comment]
Okay I see that the key size has to be max 32 bytes for AES 256

**Comment by MrWong99** [comment]
The combination AES256 + MD5 is sufficient enough for encryption since only the input is hashed to be 32 byte long, as you mentioned.
